#%RAML 1.0

title: System of Records (SOR) API
#baseUri: https://example.org/{version}
#baseUri: https://mocksvc.mulesoft.com/mocks/6360c8c2-7b1b-4456-8e20-2e4d378f5420/{version}
#baseUri: https://mocksvc.mulesoft.com/mocks/4e8e795f-f35e-4475-946d-9134e29ddf98/{version}
baseUri: https://mocksvc.mulesoft.com/mocks/23b89576-a29e-4920-9735-077c66b3f216/{version}
version: v1

types:
  customer: !include schemas/customer.schema
  #order: future extension of the API to support orders; include order schema here.
  #product: future extension of the API to support products; include product schema here.

resourceTypes:
  collection: !include resourceTypes/collection.raml
  collectionItem: !include resourceTypes/collectionItem.raml

traits:
  pageable: !include traits/pageable.raml

/customers:
  type:
    collection:
      exampleCollection: !include examples/customers.sample
      exampleItem: !include examples/customer.sample
  get:
    is: [pageable]
  /{customerId}:
    type:
      collectionItem:
        exampleItem: !include examples/customer.sample
        examplePartialItem: !include examples/partial-customer.sample
          
